name: api_contracts
description: Recharge API contracts and generated client package.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.12.0

dev_dependencies:
  lints: ^5.0.0
