class RechargeGroupSeedData {
  const RechargeGroupSeedData({
    required this.id,
    required this.title,
    required this.defaultProfileId,
    required this.applicableTypeIds,
    required this.categorySlugs,
    this.hidden = false,
  });

  final String id;
  final String title;
  final String defaultProfileId;
  final List<String> applicableTypeIds;
  final List<String> categorySlugs;
  final bool hidden;
}

class RechargeSubcategoryOverrideData {
  const RechargeSubcategoryOverrideData({
    this.profileId,
    this.applicableTypeIds,
  });

  final String? profileId;
  final List<String>? applicableTypeIds;
}

const List<RechargeGroupSeedData> rechargeGroupSeeds = <RechargeGroupSeedData>[
  RechargeGroupSeedData(
    id: 'music_nightlife',
    title: 'Music & nightlife',
    defaultProfileId: 'performance_show',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'concert',
      'live_music',
      'acoustic_evening',
      'jazz',
      'classical_music',
      'rock_music',
      'pop_music',
      'electronic_music',
      'techno',
      'house_music',
      'latin_music',
      'dj_party',
      'club_night',
      'karaoke',
      'open_mic_music',
      'rooftop_party',
      'beach_party',
      'themed_party',
      'music_festival',
      'listening_party',
      'jam_session',
      'night_bar',
      'afterwork_drinks',
      'late_night_social',
      'group_singing',
      'organ_concert',
    ],
  ),
  RechargeGroupSeedData(
    id: 'comedy_theatre_performance',
    title: 'Comedy & performance',
    defaultProfileId: 'performance_show',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'standup',
      'comedy_open_mic',
      'theatre',
      'improvisation',
      'magic_show',
      'circus',
      'poetry_night',
      'storytelling',
      'puppet_show',
      'ballet',
      'opera',
      'cabaret',
      'street_performance',
      'performance_art',
      'drag_show',
      'musical',
      'experimental_theatre',
    ],
  ),
  RechargeGroupSeedData(
    id: 'cinema_screenings',
    title: 'Cinema & screenings',
    defaultProfileId: 'performance_show',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'cinema',
      'movie_screening',
      'open_air_cinema',
      'film_festival',
      'documentary',
      'short_films',
      'retro_cinema',
      'animation',
      'sports_screening',
      'movie_discussion',
      'premiere',
      'independent_film',
      'cinema_club',
    ],
  ),
  RechargeGroupSeedData(
    id: 'art_culture_museums',
    title: 'Art, culture & museums',
    defaultProfileId: 'exhibition_visit',
    applicableTypeIds: <String>['event', 'place'],
    categorySlugs: <String>[
      'exhibition',
      'gallery',
      'museum',
      'museum_night',
      'gallery_walk',
      'artist_talk',
      'art_walk',
      'photography_exhibition',
      'street_art',
      'architecture',
      'cultural_heritage',
      'literature_evening',
      'book_reading',
      'history_walk',
      'design_event',
      'craft_exhibition',
      'public_art',
      'creative_meetup',
      'fashion_event',
    ],
  ),
  RechargeGroupSeedData(
    id: 'education_talks',
    title: 'Education & talks',
    defaultProfileId: 'talk_lecture',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'lecture',
      'public_talk',
      'discussion',
      'debate',
      'panel_discussion',
      'science_talk',
      'history_lecture',
      'psychology_talk',
      'finance_talk',
      'career_talk',
      'legal_info_session',
      'book_club',
      'practical_seminar',
      'self_development',
      'health_talk',
      'technology_talk',
      'startup_talk',
      'parenting_talk',
      'community_discussion',
    ],
  ),
  RechargeGroupSeedData(
    id: 'business_networking',
    title: 'Business & networking',
    defaultProfileId: 'networking_social',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'networking',
      'business_breakfast',
      'business_lunch',
      'conference',
      'product_presentation',
      'product_launch',
      'startup_meetup',
      'pitch_night',
      'investor_meetup',
      'job_fair',
      'portfolio_review',
      'freelancers_meetup',
      'demo_day',
      'expo',
      'founder_meetup',
      'industry_meetup',
      'career_networking',
      'coworking_event',
      'business_workshop',
    ],
  ),
  RechargeGroupSeedData(
    id: 'workshops_masterclasses',
    title: 'Workshops & masterclasses',
    defaultProfileId: 'hands_on_class',
    applicableTypeIds: <String>['event', 'classWorkshop', 'session'],
    categorySlugs: <String>[
      'workshop',
      'masterclass',
      'course',
      'pottery',
      'ceramics',
      'drawing',
      'painting',
      'photography',
      'cooking_class',
      'sewing',
      'floristics',
      'candle_making',
      'public_speaking',
      'creative_class',
      'craft_workshop',
      'writing_workshop',
      'music_lesson',
      'dance_workshop',
      'beauty_workshop',
      'wellness_workshop',
    ],
  ),
  RechargeGroupSeedData(
    id: 'language_social_learning',
    title: 'Languages & social learning',
    defaultProfileId: 'networking_social',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'language_exchange',
      'english_club',
      'dutch_club',
      'latvian_club',
      'conversation_club',
      'international_meetup',
      'expats_meetup',
      'tandem_meeting',
      'language_cafe',
      'language_walk',
      'speed_friending',
      'speaking_club',
      'culture_exchange',
      'newcomers_meetup',
      'study_group',
    ],
  ),
  RechargeGroupSeedData(
    id: 'food_drinks',
    title: 'Food & drinks',
    defaultProfileId: 'food_gathering',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'coffee',
      'breakfast',
      'brunch',
      'lunch',
      'dinner',
      'dessert',
      'street_food',
      'food_tasting',
      'drink_tasting',
      'wine_tasting',
      'beer_tasting',
      'cocktail_tasting',
      'tea_ceremony',
      'bbq',
      'picnic',
      'food_tour',
      'bar_crawl',
      'pub_crawl',
      'happy_hour',
      'restaurant_visit',
      'cafe_visit',
      'bakery_visit',
      'vegan_food',
      'local_food',
      'fine_dining',
      'family_meal',
    ],
  ),
  RechargeGroupSeedData(
    id: 'games_indoor',
    title: 'Games & indoor',
    defaultProfileId: 'game_session',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'quiz',
      'board_games',
      'mafia',
      'poker_no_gambling',
      'chess',
      'escape_room',
      'quest',
      'city_game',
      'treasure_hunt',
      'bowling',
      'billiards',
      'darts',
      'mini_golf',
      'arcade',
      'vr_arcade',
      'video_games',
      'table_games',
      'card_games',
      'role_playing_game',
      'indoor_competition',
    ],
  ),
  RechargeGroupSeedData(
    id: 'sport',
    title: 'Sport',
    defaultProfileId: 'physical_activity',
    applicableTypeIds: <String>['event', 'activity', 'session'],
    categorySlugs: <String>[
      'football',
      'basketball',
      'volleyball',
      'beach_volleyball',
      'tennis',
      'table_tennis',
      'badminton',
      'squash',
      'padel',
      'running',
      'trail_running',
      'cycling',
      'swimming',
      'boxing',
      'martial_arts',
      'climbing',
      'bouldering',
      'fitness',
      'gym',
      'crossfit',
      'calisthenics',
      'yoga',
      'pilates',
      'stretching',
      'dance_fitness',
      'nordic_walking',
      'skating',
      'skateboarding',
      'rollerblading',
      'golf',
      'frisbee',
      'disc_golf',
      'running_race',
      'cycling_race',
      'fitness_challenge',
      'amateur_tournament',
    ],
  ),
  RechargeGroupSeedData(
    id: 'dance',
    title: 'Dance',
    defaultProfileId: 'physical_activity',
    applicableTypeIds: <String>['event', 'classWorkshop', 'session'],
    categorySlugs: <String>[
      'salsa',
      'bachata',
      'kizomba',
      'tango',
      'hip_hop',
      'contemporary_dance',
      'ballroom_dance',
      'folk_dance',
      'dance_social',
      'dance_battle',
      'zumba',
      'partner_dance',
      'latin_dance',
      'heels_dance',
      'street_dance',
      'dance_class',
      'dance_practice',
      'dance_show',
    ],
  ),
  RechargeGroupSeedData(
    id: 'outdoor_nature_walking',
    title: 'Outdoor, nature & walking',
    defaultProfileId: 'outdoor_activity',
    applicableTypeIds: <String>['event', 'activity', 'route'],
    categorySlugs: <String>[
      'hiking',
      'nature_walk',
      'city_walk',
      'historical_walk',
      'sunset_walk',
      'sunrise_walk',
      'forest_walk',
      'lake_walk',
      'river_walk',
      'architecture_walk',
      'hidden_gems_walk',
      'photography_walk',
      'birdwatching',
      'mushroom_picking',
      'berry_picking',
      'picnic_walk',
      'park_walk',
      'beach_walk',
      'promenade_walk',
      'outdoor_workout',
      'nature_escape',
      'slow_walk',
      'stargazing',
      'northern_lights_watch',
      'meteor_shower_watch',
    ],
  ),
  RechargeGroupSeedData(
    id: 'water_activities',
    title: 'Water activities',
    defaultProfileId: 'water_activity',
    applicableTypeIds: <String>['event', 'activity', 'session'],
    categorySlugs: <String>[
      'sup',
      'kayak',
      'canoe',
      'boat_trip',
      'catamaran',
      'canal_cruise',
      'rowing',
      'sailing',
      'fishing',
      'wakeboarding',
      'water_bike',
      'jet_ski',
      'beach_activity',
      'water_tour',
      'diving',
      'snorkeling',
      'surfing',
      'windsurfing',
      'kitesurfing',
      'beach_day',
    ],
  ),
  RechargeGroupSeedData(
    id: 'winter_seasonal',
    title: 'Winter & seasonal',
    defaultProfileId: 'outdoor_activity',
    applicableTypeIds: <String>['event', 'activity'],
    categorySlugs: <String>[
      'winter_walk',
      'ice_skating',
      'skiing',
      'snowboarding',
      'sledding',
      'winter_hiking',
      'christmas_market_walk',
      'winter_photo_route',
      'sauna_cold_plunge',
      'ice_fishing',
      'winter_festival',
      'autumn_leaf_walk',
      'spring_blossom_walk',
      'summer_outdoor',
      'seasonal_walk',
      'snow_activity',
      'cold_plunge',
      'holiday_lights_walk',
    ],
  ),
  RechargeGroupSeedData(
    id: 'travel_tours',
    title: 'Travel & tours',
    defaultProfileId: 'guided_tour',
    applicableTypeIds: <String>['event', 'route'],
    categorySlugs: <String>[
      'day_trip',
      'weekend_trip',
      'local_experience',
      'tourist_excursion',
      'city_tour',
      'food_tasting_tour',
      'craft_experience',
      'farm_experience',
      'castle_tour',
      'nature_reserve_tour',
      'coastal_trip',
      'train_day_trip',
      'local_guide_experience',
      'bike_tour',
      'walking_tour',
      'historical_tour',
      'architecture_tour',
      'photo_tour',
      'hidden_gems_tour',
    ],
  ),
  RechargeGroupSeedData(
    id: 'family_kids',
    title: 'Family & kids',
    defaultProfileId: 'kids_event',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'family_activity',
      'kids_workshop',
      'playground_event',
      'family_picnic',
      'kids_theatre',
      'kids_museum_event',
      'family_sports_day',
      'parent_child_class',
      'creative_kids_class',
      'kids_cooking_class',
      'kids_outdoor_walk',
      'birthday_activity',
      'family_farm_visit',
      'family_route',
      'kids_party',
      'educational_kids_event',
      'baby_friendly_activity',
      'kids_camp',
      'day_camp',
      'teen_meetup',
      'teen_event',
      'kids_quest',
      'kids_science_event',
      'kids_disco',
    ],
  ),
  RechargeGroupSeedData(
    id: 'pets_animals',
    title: 'Pets & animals',
    defaultProfileId: 'pet_event',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'dog_walk',
      'dog_meetup',
      'dog_park_meetup',
      'pet_friendly_cafe',
      'dog_training',
      'pet_photo_session',
      'animal_shelter_visit',
      'farm_animal_experience',
      'horse_riding',
      'pony_riding',
      'cat_cafe',
      'pet_adoption',
      'pet_charity',
      'pet_friendly_walk',
      'dog_sport',
      'pet_owner_meetup',
      'dog_show',
      'pet_exhibition',
      'pet_fair',
      'pet_care_talk',
      'animal_therapy',
    ],
  ),
  RechargeGroupSeedData(
    id: 'community_charity',
    title: 'Community & charity',
    defaultProfileId: 'volunteer_action',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'charity_event',
      'volunteer_activity',
      'community_cleanup',
      'donation_event',
      'neighborhood_event',
      'fundraising_dinner',
      'charity_run',
      'animal_shelter_volunteering',
      'food_bank_volunteering',
      'tree_planting',
      'beach_cleanup',
      'park_cleanup',
      'community_garden',
      'local_community_meetup',
      'mutual_aid',
      'social_impact_event',
      'environmental_action',
    ],
  ),
  RechargeGroupSeedData(
    id: 'markets_fairs',
    title: 'Markets & fairs',
    defaultProfileId: 'market_fair',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'local_market',
      'flea_market',
      'seasonal_market',
      'christmas_market',
      'farmers_market',
      'craft_market',
      'design_market',
      'vintage_market',
      'book_market',
      'food_market',
      'flower_market',
      'art_fair',
      'pop_up_shop',
      'street_market',
      'handmade_fair',
      'charity_market',
      'kids_market',
      'night_market',
      'local_brands_market',
      'clothing_swap',
    ],
  ),
  RechargeGroupSeedData(
    id: 'holidays_seasonal',
    title: 'Holidays & seasonal',
    defaultProfileId: 'open_event',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'christmas',
      'new_year',
      'halloween',
      'easter',
      'valentines_day',
      'jani',
      'city_festival',
      'summer_festival',
      'autumn_event',
      'spring_event',
      'school_holiday',
      'national_holiday',
      'local_tradition',
      'midsummer',
      'fireworks',
      'public_celebration',
    ],
  ),
  RechargeGroupSeedData(
    id: 'wellness_recharge',
    title: 'Wellness & recharge',
    defaultProfileId: 'wellness_session',
    applicableTypeIds: <String>['event', 'activity', 'session'],
    categorySlugs: <String>[
      'recharge_walk',
      'calm_walk',
      'mindful_walk',
      'coffee_walk',
      'tea_walk',
      'sunset_reset',
      'nature_reset',
      'digital_detox',
      'slow_morning',
      'evening_reset',
      'sauna',
      'spa',
      'massage',
      'breathwork',
      'meditation',
      'sound_healing',
      'wellness_class',
      'relaxation_session',
      'mental_health_meetup',
      'quiet_social',
      'couple_recharge',
      'solo_recharge',
      'friends_recharge',
      'pirts_ritual',
      'retreat',
    ],
  ),
  RechargeGroupSeedData(
    id: 'adrenaline_entertainment',
    title: 'Adrenaline & entertainment',
    defaultProfileId: 'adrenaline_activity',
    applicableTypeIds: <String>['event', 'session'],
    categorySlugs: <String>[
      'laser_tag',
      'paintball',
      'airsoft',
      'karting',
      'shooting_range',
      'archery',
      'axe_throwing',
      'trampoline_park',
      'rope_park',
      'zipline',
      'wind_tunnel',
      'hot_air_balloon',
      'skydiving',
      'bungee_jumping',
      'parkour',
      'obstacle_course',
    ],
  ),
  RechargeGroupSeedData(
    id: 'attractions',
    title: 'Attractions',
    defaultProfileId: 'exhibition_visit',
    applicableTypeIds: <String>['place', 'event'],
    categorySlugs: <String>[
      'zoo',
      'petting_zoo',
      'aquarium',
      'amusement_park',
      'water_park',
      'adventure_park',
      'botanical_garden',
      'planetarium',
      'science_center',
      'observation_deck',
      'ferris_wheel',
      'seasonal_attraction',
    ],
  ),
  RechargeGroupSeedData(
    id: 'auto_moto',
    title: 'Auto & moto',
    defaultProfileId: 'networking_social',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'car_meetup',
      'retro_cars',
      'car_show',
      'auto_exhibition',
      'tuning_meetup',
      'drift_event',
      'offroad_trip',
      'motorcycle_ride',
      'motorcycle_meetup',
      'scooter_meetup',
      'car_photo_meet',
      'drive_in_cinema',
    ],
  ),
  RechargeGroupSeedData(
    id: 'geek_tech',
    title: 'Geek & tech',
    defaultProfileId: 'networking_social',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'anime_meetup',
      'cosplay_event',
      'comic_con',
      'esports_tournament',
      'lan_party',
      'retro_gaming',
      'tabletop_wargames',
      'trading_card_games',
      'hackathon',
      'game_dev_meetup',
      'tech_meetup',
      'robotics_event',
      'fandom_meetup',
      'collectors_meetup',
    ],
  ),
  RechargeGroupSeedData(
    id: 'dating_singles',
    title: 'Dating & singles',
    defaultProfileId: 'networking_social',
    applicableTypeIds: <String>['event'],
    categorySlugs: <String>[
      'speed_dating',
      'singles_party',
      'singles_mixer',
      'singles_dinner',
      'blind_date_event',
      'dating_game_event',
      'singles_activity',
      'matchmaking_event',
    ],
  ),
  RechargeGroupSeedData(
    id: 'other',
    title: 'Other',
    defaultProfileId: 'open_event',
    applicableTypeIds: <String>[
      'event',
      'activity',
      'route',
      'place',
      'session',
      'classWorkshop',
    ],
    categorySlugs: <String>['other_event'],
    hidden: true,
  ),
];

const Map<String, RechargeSubcategoryOverrideData>
rechargeSubcategoryOverrides = <String, RechargeSubcategoryOverrideData>{
  'afterwork_drinks': RechargeSubcategoryOverrideData(
    profileId: 'networking_social',
  ),
  'amateur_tournament': RechargeSubcategoryOverrideData(
    profileId: 'competition',
    applicableTypeIds: <String>['event'],
  ),
  'animal_shelter_visit': RechargeSubcategoryOverrideData(
    profileId: 'volunteer_action',
  ),
  'arcade': RechargeSubcategoryOverrideData(
    profileId: 'venue_game',
    applicableTypeIds: <String>['event', 'place'],
  ),
  'architecture_walk': RechargeSubcategoryOverrideData(
    profileId: 'guided_tour',
  ),
  'art_walk': RechargeSubcategoryOverrideData(
    profileId: 'guided_tour',
    applicableTypeIds: <String>['event', 'route'],
  ),
  'artist_talk': RechargeSubcategoryOverrideData(
    profileId: 'talk_lecture',
    applicableTypeIds: <String>['event'],
  ),
  'auto_exhibition': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'bakery_visit': RechargeSubcategoryOverrideData(
    profileId: 'food_gathering',
    applicableTypeIds: <String>['place', 'event'],
  ),
  'bar_crawl': RechargeSubcategoryOverrideData(profileId: 'tasting'),
  'basketball': RechargeSubcategoryOverrideData(
    profileId: 'team_game',
    applicableTypeIds: <String>['event'],
  ),
  'beach_activity': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['event', 'activity'],
  ),
  'beach_day': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['event', 'activity'],
  ),
  'beach_volleyball': RechargeSubcategoryOverrideData(
    profileId: 'team_game',
    applicableTypeIds: <String>['event'],
  ),
  'beer_tasting': RechargeSubcategoryOverrideData(profileId: 'tasting'),
  'billiards': RechargeSubcategoryOverrideData(
    profileId: 'venue_game',
    applicableTypeIds: <String>['event', 'place'],
  ),
  'boat_trip': RechargeSubcategoryOverrideData(
    profileId: 'guided_tour',
    applicableTypeIds: <String>['event', 'session'],
  ),
  'book_club': RechargeSubcategoryOverrideData(profileId: 'networking_social'),
  'book_reading': RechargeSubcategoryOverrideData(
    profileId: 'talk_lecture',
    applicableTypeIds: <String>['event'],
  ),
  'bowling': RechargeSubcategoryOverrideData(
    profileId: 'venue_game',
    applicableTypeIds: <String>['event', 'place'],
  ),
  'business_workshop': RechargeSubcategoryOverrideData(
    profileId: 'hands_on_class',
  ),
  'cafe_visit': RechargeSubcategoryOverrideData(
    profileId: 'food_gathering',
    applicableTypeIds: <String>['place', 'event'],
  ),
  'calm_walk': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['activity', 'event', 'route'],
  ),
  'canal_cruise': RechargeSubcategoryOverrideData(
    profileId: 'guided_tour',
    applicableTypeIds: <String>['event', 'session'],
  ),
  'car_show': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'cat_cafe': RechargeSubcategoryOverrideData(
    profileId: 'pet_event',
    applicableTypeIds: <String>['place', 'event'],
  ),
  'charity_run': RechargeSubcategoryOverrideData(profileId: 'competition'),
  'cinema': RechargeSubcategoryOverrideData(
    profileId: 'exhibition_visit',
    applicableTypeIds: <String>['place', 'event'],
  ),
  'cinema_club': RechargeSubcategoryOverrideData(profileId: 'talk_lecture'),
  'city_festival': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'city_game': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['event', 'route'],
  ),
  'cocktail_tasting': RechargeSubcategoryOverrideData(profileId: 'tasting'),
  'coffee_walk': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['activity', 'event', 'route'],
  ),
  'cold_plunge': RechargeSubcategoryOverrideData(
    profileId: 'wellness_session',
    applicableTypeIds: <String>['event', 'session'],
  ),
  'comic_con': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'conference': RechargeSubcategoryOverrideData(profileId: 'talk_lecture'),
  'creative_meetup': RechargeSubcategoryOverrideData(
    profileId: 'networking_social',
    applicableTypeIds: <String>['event'],
  ),
  'cycling_race': RechargeSubcategoryOverrideData(
    profileId: 'competition',
    applicableTypeIds: <String>['event'],
  ),
  'dance_battle': RechargeSubcategoryOverrideData(
    profileId: 'competition',
    applicableTypeIds: <String>['event'],
  ),
  'dance_show': RechargeSubcategoryOverrideData(
    profileId: 'performance_show',
    applicableTypeIds: <String>['event'],
  ),
  'dance_social': RechargeSubcategoryOverrideData(
    profileId: 'networking_social',
    applicableTypeIds: <String>['event'],
  ),
  'darts': RechargeSubcategoryOverrideData(
    profileId: 'venue_game',
    applicableTypeIds: <String>['event', 'place'],
  ),
  'day_camp': RechargeSubcategoryOverrideData(
    applicableTypeIds: <String>['event', 'session'],
  ),
  'demo_day': RechargeSubcategoryOverrideData(profileId: 'talk_lecture'),
  'dog_show': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'drift_event': RechargeSubcategoryOverrideData(profileId: 'performance_show'),
  'drink_tasting': RechargeSubcategoryOverrideData(profileId: 'tasting'),
  'drive_in_cinema': RechargeSubcategoryOverrideData(
    profileId: 'performance_show',
  ),
  'escape_room': RechargeSubcategoryOverrideData(
    profileId: 'venue_game',
    applicableTypeIds: <String>['event', 'place', 'session'],
  ),
  'esports_tournament': RechargeSubcategoryOverrideData(
    profileId: 'competition',
  ),
  'expo': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'family_route': RechargeSubcategoryOverrideData(
    applicableTypeIds: <String>['route', 'event'],
  ),
  'fashion_event': RechargeSubcategoryOverrideData(
    profileId: 'performance_show',
    applicableTypeIds: <String>['event'],
  ),
  'film_festival': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'fitness_challenge': RechargeSubcategoryOverrideData(
    profileId: 'competition',
    applicableTypeIds: <String>['event'],
  ),
  'food_tasting': RechargeSubcategoryOverrideData(profileId: 'tasting'),
  'food_tour': RechargeSubcategoryOverrideData(
    profileId: 'guided_tour',
    applicableTypeIds: <String>['event', 'route'],
  ),
  'football': RechargeSubcategoryOverrideData(
    profileId: 'team_game',
    applicableTypeIds: <String>['event'],
  ),
  'frisbee': RechargeSubcategoryOverrideData(
    profileId: 'team_game',
    applicableTypeIds: <String>['event'],
  ),
  'fundraising_dinner': RechargeSubcategoryOverrideData(
    profileId: 'food_gathering',
  ),
  'gallery_walk': RechargeSubcategoryOverrideData(
    profileId: 'guided_tour',
    applicableTypeIds: <String>['event', 'route'],
  ),
  'group_singing': RechargeSubcategoryOverrideData(
    profileId: 'networking_social',
  ),
  'gym': RechargeSubcategoryOverrideData(
    profileId: 'physical_activity',
    applicableTypeIds: <String>['place', 'session'],
  ),
  'hackathon': RechargeSubcategoryOverrideData(profileId: 'competition'),
  'happy_hour': RechargeSubcategoryOverrideData(profileId: 'tasting'),
  'hidden_gems_walk': RechargeSubcategoryOverrideData(profileId: 'guided_tour'),
  'historical_walk': RechargeSubcategoryOverrideData(profileId: 'guided_tour'),
  'history_walk': RechargeSubcategoryOverrideData(
    profileId: 'guided_tour',
    applicableTypeIds: <String>['event', 'route'],
  ),
  'horse_riding': RechargeSubcategoryOverrideData(
    profileId: 'adrenaline_activity',
    applicableTypeIds: <String>['event', 'session'],
  ),
  'ice_skating': RechargeSubcategoryOverrideData(
    profileId: 'physical_activity',
    applicableTypeIds: <String>['event', 'activity', 'session'],
  ),
  'indoor_competition': RechargeSubcategoryOverrideData(
    profileId: 'competition',
  ),
  'jam_session': RechargeSubcategoryOverrideData(
    profileId: 'networking_social',
  ),
  'job_fair': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'karaoke': RechargeSubcategoryOverrideData(profileId: 'networking_social'),
  'kids_camp': RechargeSubcategoryOverrideData(
    applicableTypeIds: <String>['event', 'session'],
  ),
  'lan_party': RechargeSubcategoryOverrideData(profileId: 'game_session'),
  'language_walk': RechargeSubcategoryOverrideData(
    profileId: 'guided_tour',
    applicableTypeIds: <String>['event', 'activity'],
  ),
  'late_night_social': RechargeSubcategoryOverrideData(
    profileId: 'networking_social',
  ),
  'literature_evening': RechargeSubcategoryOverrideData(
    profileId: 'talk_lecture',
    applicableTypeIds: <String>['event'],
  ),
  'local_community_meetup': RechargeSubcategoryOverrideData(
    profileId: 'networking_social',
  ),
  'massage': RechargeSubcategoryOverrideData(
    profileId: 'wellness_session',
    applicableTypeIds: <String>['session', 'event', 'place'],
  ),
  'mental_health_meetup': RechargeSubcategoryOverrideData(
    profileId: 'networking_social',
    applicableTypeIds: <String>['event'],
  ),
  'mindful_walk': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['activity', 'event', 'route'],
  ),
  'mini_golf': RechargeSubcategoryOverrideData(
    profileId: 'venue_game',
    applicableTypeIds: <String>['event', 'place'],
  ),
  'motorcycle_ride': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['event', 'route'],
  ),
  'movie_discussion': RechargeSubcategoryOverrideData(
    profileId: 'talk_lecture',
  ),
  'music_festival': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'night_bar': RechargeSubcategoryOverrideData(
    profileId: 'networking_social',
    applicableTypeIds: <String>['event', 'place'],
  ),
  'offroad_trip': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['event', 'route'],
  ),
  'outdoor_workout': RechargeSubcategoryOverrideData(
    profileId: 'physical_activity',
  ),
  'parkour': RechargeSubcategoryOverrideData(
    applicableTypeIds: <String>['event', 'activity', 'classWorkshop'],
  ),
  'pet_care_talk': RechargeSubcategoryOverrideData(profileId: 'talk_lecture'),
  'pet_charity': RechargeSubcategoryOverrideData(profileId: 'volunteer_action'),
  'pet_exhibition': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'pet_fair': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'pet_friendly_cafe': RechargeSubcategoryOverrideData(
    profileId: 'pet_event',
    applicableTypeIds: <String>['place', 'event'],
  ),
  'pet_photo_session': RechargeSubcategoryOverrideData(
    profileId: 'pet_event',
    applicableTypeIds: <String>['event', 'session'],
  ),
  'pilates': RechargeSubcategoryOverrideData(profileId: 'wellness_session'),
  'pirts_ritual': RechargeSubcategoryOverrideData(
    profileId: 'wellness_session',
    applicableTypeIds: <String>['session', 'event', 'place'],
  ),
  'pitch_night': RechargeSubcategoryOverrideData(profileId: 'competition'),
  'pony_riding': RechargeSubcategoryOverrideData(
    profileId: 'adrenaline_activity',
    applicableTypeIds: <String>['event', 'session'],
  ),
  'practical_seminar': RechargeSubcategoryOverrideData(
    profileId: 'hands_on_class',
  ),
  'product_launch': RechargeSubcategoryOverrideData(profileId: 'talk_lecture'),
  'product_presentation': RechargeSubcategoryOverrideData(
    profileId: 'talk_lecture',
  ),
  'pub_crawl': RechargeSubcategoryOverrideData(profileId: 'tasting'),
  'quiet_social': RechargeSubcategoryOverrideData(
    profileId: 'networking_social',
    applicableTypeIds: <String>['event'],
  ),
  'quiz': RechargeSubcategoryOverrideData(profileId: 'competition'),
  'recharge_walk': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['activity', 'event', 'route'],
  ),
  'restaurant_visit': RechargeSubcategoryOverrideData(
    profileId: 'food_gathering',
    applicableTypeIds: <String>['place', 'event'],
  ),
  'retro_gaming': RechargeSubcategoryOverrideData(profileId: 'game_session'),
  'rope_park': RechargeSubcategoryOverrideData(
    applicableTypeIds: <String>['event', 'place', 'session'],
  ),
  'running_race': RechargeSubcategoryOverrideData(
    profileId: 'competition',
    applicableTypeIds: <String>['event'],
  ),
  'sauna': RechargeSubcategoryOverrideData(
    profileId: 'wellness_session',
    applicableTypeIds: <String>['session', 'event', 'place'],
  ),
  'sauna_cold_plunge': RechargeSubcategoryOverrideData(
    profileId: 'wellness_session',
    applicableTypeIds: <String>['event', 'session'],
  ),
  'skiing': RechargeSubcategoryOverrideData(
    profileId: 'physical_activity',
    applicableTypeIds: <String>['event', 'activity', 'session'],
  ),
  'snowboarding': RechargeSubcategoryOverrideData(
    profileId: 'physical_activity',
    applicableTypeIds: <String>['event', 'activity', 'session'],
  ),
  'spa': RechargeSubcategoryOverrideData(
    profileId: 'wellness_session',
    applicableTypeIds: <String>['session', 'event', 'place'],
  ),
  'stretching': RechargeSubcategoryOverrideData(profileId: 'wellness_session'),
  'study_group': RechargeSubcategoryOverrideData(profileId: 'talk_lecture'),
  'summer_festival': RechargeSubcategoryOverrideData(profileId: 'market_fair'),
  'tabletop_wargames': RechargeSubcategoryOverrideData(
    profileId: 'game_session',
  ),
  'tea_walk': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['activity', 'event', 'route'],
  ),
  'trading_card_games': RechargeSubcategoryOverrideData(
    profileId: 'game_session',
  ),
  'trampoline_park': RechargeSubcategoryOverrideData(
    applicableTypeIds: <String>['event', 'place', 'session'],
  ),
  'treasure_hunt': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['event', 'route'],
  ),
  'volleyball': RechargeSubcategoryOverrideData(
    profileId: 'team_game',
    applicableTypeIds: <String>['event'],
  ),
  'vr_arcade': RechargeSubcategoryOverrideData(
    profileId: 'venue_game',
    applicableTypeIds: <String>['event', 'place'],
  ),
  'water_tour': RechargeSubcategoryOverrideData(
    profileId: 'guided_tour',
    applicableTypeIds: <String>['event', 'session'],
  ),
  'wine_tasting': RechargeSubcategoryOverrideData(profileId: 'tasting'),
  'winter_festival': RechargeSubcategoryOverrideData(
    profileId: 'market_fair',
    applicableTypeIds: <String>['event'],
  ),
  'winter_photo_route': RechargeSubcategoryOverrideData(
    profileId: 'outdoor_activity',
    applicableTypeIds: <String>['route', 'event'],
  ),
  'yoga': RechargeSubcategoryOverrideData(profileId: 'wellness_session'),
};

const Map<String, String> rechargeContextAliases = <String, String>{
  'food_drinks.cooking_class': 'cooking_class',
  'business_networking.hackathon': 'hackathon',
  'auto_moto.karting': 'karting',
  'cinema_screenings.drive_in_cinema': 'drive_in_cinema',
  'pets_animals.animal_volunteering': 'animal_shelter_volunteering',
};

const Map<String, Map<String, String>> rechargeSubcategoryImpliedFacets =
    <String, Map<String, String>>{
      'sunset_walk': <String, String>{'timeOfDay': 'evening'},
      'sunrise_walk': <String, String>{'timeOfDay': 'morning'},
      'family_activity': <String, String>{'withWhom': 'family'},
      'couple_recharge': <String, String>{'withWhom': 'couple'},
      'solo_recharge': <String, String>{'withWhom': 'solo'},
      'friends_recharge': <String, String>{'withWhom': 'friends'},
      'sunset_reset': <String, String>{'timeOfDay': 'evening'},
      'slow_morning': <String, String>{'timeOfDay': 'morning'},
      'speed_dating': <String, String>{'withWhom': 'solo'},
    };

const Map<String, Map<String, String>> rechargeGroupImpliedFacets =
    <String, Map<String, String>>{
      'family_kids': <String, String>{'withWhom': 'family'},
      'dating_singles': <String, String>{'withWhom': 'solo'},
    };

const Map<String, String> rechargeSubcategorySeasonality = <String, String>{
  'winter_walk': 'winter',
  'ice_skating': 'winter',
  'skiing': 'winter',
  'snowboarding': 'winter',
  'sledding': 'winter',
  'winter_hiking': 'winter',
  'christmas_market_walk': 'winter',
  'winter_photo_route': 'winter',
  'sauna_cold_plunge': 'winter',
  'ice_fishing': 'winter',
  'winter_festival': 'winter',
  'snow_activity': 'winter',
  'holiday_lights_walk': 'winter',
  'autumn_leaf_walk': 'autumn',
  'spring_blossom_walk': 'spring',
  'summer_outdoor': 'summer',
  'christmas': 'winter',
  'new_year': 'winter',
  'halloween': 'autumn',
  'easter': 'spring',
  'jani': 'summer',
  'summer_festival': 'summer',
  'autumn_event': 'autumn',
  'spring_event': 'spring',
  'midsummer': 'summer',
};
